AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to setup and deploy vSBC HA instances and
  2 PKTART instances to test vSBC. This template creates required vpc, subnet and
  other routing elements required IAM role to performce IP movement betweenn two vSBC
  instances.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Common and PKTART data
        Parameters:
          - KeyPairName
      - Label:
          default: SBC Configuration
        Parameters:
          - SBCInstanceType
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCIDR
          - ManagementSubnetCIDR
          - SBCHASubnetCIDR
          - SBCExVoipCIDR
          - SBCAvailabilityZone
          - AvailabilityZones
      - Label:
          default: 'Optional: SBC configuration. For default configuration no need
            to change these values.'
        Parameters:
          - SBCPersonalityType
          - SBCActiveInstanceName
          - SBCPassiveInstanceName
          - SBCSystemName
          - Tenancy
          - PlacementId
          - SBCVolumeType
          - SBCVolumeIOPS
          - SBCVolumeSize
Parameters:
  # VPC.
  KeyPairName:
    Description: 'Name of an existing EC2 KeyPair to enable SSH access to the SBC
      and Mangler instance '
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  VPCCIDR:
    Description: VPC CIDR block for new VPC that will be used to create SBC and PKTART
      test tool.
    Type: String
    Default: 10.74.0.0/16
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  AvailabilityZones:
    Description: >-
      List of Availability Zones to use for the subnets in the VPC. Only two
      Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  SBCExVoipCIDR:
    Description: Enter a CIDR for pirvate subnet for SBC, this new subnet will be
      served by Mangler instance.
    Type: String
    MinLength: '1'
    Default: 10.74.40.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  SBCInVoipCIDR:
    Description: Enter a CIDR for pirvate subnet for SBC, this new subnet will be
      served by Mangler instance.
    Type: String
    MinLength: '1'
    Default: 10.74.40.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  HFEPublicCIDR:
    Description: Enter a CIDR for pirvate subnet for SBC, this new subnet will be
      served by Mangler instance.
    Type: String
    MinLength: '1'
    Default: 10.74.50.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  HFEPrivateCIDR:
    Description: Enter a CIDR for pirvate subnet for SBC, this new subnet will be
      served by Mangler instance.
    Type: String
    MinLength: '1'
    Default: 10.74.60.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  ManagementSubnetCIDR:
    Description: CIDR used within the Management Subnet
    Type: String
    MinLength: '1'
    Default: 10.74.10.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  SBCHASubnetCIDR:
    Description: CIDR used within the SBC High Availability subnet.
    Type: String
    MinLength: '1'
    Default: 10.74.20.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  SBCExternalVoipCIDR:
    Description: CIDR used within the SBC External Voip (public facing) subnet.
    Type: String
    MinLength: '1'
    Default: 10.74.20.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  SBCInternalVoipCIDR:
    Description: CIDR used within the SBC Internal Voip (private) subnet.
      served by Mangler instance.
    Type: String
    MinLength: '1'
    Default: 10.74.20.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  PublicHFEPacketSubnetCIDR:
    Description: CIDR used within the HFE Public Subnet.
    Type: String
    MinLength: '1'
    Default: 10.74.50.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  PrivateHFESubnetCIDR:
    Description: CIDR used for the HFE Private Subnet.
    Type: String
    MinLength: '1'
    Default: 10.74.60.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x and
      subnet of VPC.
  HFEManagementNeedsEIP:
    Description: Enable EIP on the management interface of the HFE instance(s)?
    Type: String
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  HFEManagementEIPAccessCIDR:
    Description: The CIDR range used to access the HFE Management EIP.
    Type: String
    Default: ''
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
  SBCExVoipSubnet:
    Type: String
  SBCManagementSubnet:
    Type: String
  SBCHASubnet:
    Type: String
  HFEPublicSubnet:
    Type: String
  HFEPrivateSubnet:
    Type: String
# TODO: Removed in leiu of VPC Template. come back to this.
  SBCAvailabilityZone:
    Description: Enter Availability Zone for SBC, New subnets for SBC will be created
      here.
    Type: AWS::EC2::AvailabilityZone::Name
  SBCInstanceType:
    Description: Instance type for the SBC Mangler.
    Type: String
    Default: m5.xlarge
    AllowedValues:
      - m4.xlarge
      - m5.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.8xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
  SBCPersonalityType:
    Description: SBC Personality Type. Currently only supports 'isbc' (Integrated). Distributed is currently not supported.
    Type: String
    Default: isbc
    AllowedValues:
      - isbc
    ConstraintDescription: Must be a valid SBC Personality type.
  SBCActiveInstanceName:
    Description: CE name of the active instance
    Type: String
    Default: vsbc1
    MaxLength: '63'
    AllowedPattern: ^[A-Za-z]{1}[-A-Za-z0-9.]*[A-Za-z0-9]{1}$
    ConstraintDescription: 'Enter valid ceName(instance name).  Regex: ^[A-Za-z]{1}[-A-Za-z0-9.]*[A-Za-z0-9]{1}$'
  SBCPassiveInstanceName:
    Description: CE name of the standby instance
    Type: String
    Default: vsbc2
    MaxLength: '63'
    AllowedPattern: ^[A-Za-z]{1}[-A-Za-z0-9.]*[A-Za-z0-9]{1}$
    ConstraintDescription: 'Enter valid ceName(instance name).  Regex: ^[A-Za-z]{1}[-A-Za-z0-9.]*[A-Za-z0-9]{1}$'
  SBCSystemName:
    Description: System Name
    Type: String
    Default: vsbcSystem
    MaxLength: '26'
    AllowedPattern: ^[A-Za-z]{1}[-A-Za-z0-9]*[A-Za-z0-9]{1}$
    ConstraintDescription: 'Enter valid system name.  Regex: ^[A-Za-z]{1}[-A-Za-z0-9]*[A-Za-z0-9]{1}$ '
  # TODO: Rename. De-couple scope.
  SSHAccessCIDR:
    Description: IP CIDR from where you could SSH into SBC and PKTART instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: '0.0.0.0/0'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  # TODO: Removed due to VPC Template.
  Tenancy:
    Description: Tenancy attribute for SBC instances
    Type: String
    Default: default
    AllowedValues:
      - default
      - dedicated
  # TODO: Removed due to VPC Template.
  # - Is this something we should support?
  # - Does the VPC Template handle this already?
  # - Can we condition it?
  PlacementId:
    Description: PlacementGroup to launch SBC instances(Optional)
    Type: String
    Default: ''
  SBCVolumeType:
    Description: Select Type of Volume for SBC
    Type: String
    Default: io1
    AllowedValues:
      - gp2
      - io1
  CreateVPCEndPoint:
    Description: Do you want to create VPC End-point to access API server? if you
      select no then SBC will reach API server using EIP on mgt0 ports
    Type: String
    Default: 'yes'
    AllowedValues:
      - 'yes'
      - 'no'
  SBCVolumeIOPS:
    Description: Enter IOPS reservation for IO1 type EBS volume [<= 1950]. This value is ignored for GP2 type volumes.
    Type: Number
    Default: '600'
    MaxValue: '1950'
  SBCVolumeSize:
    Description: Enter size of disk in GiB. Minimum disk required is 65 GiB
    Type: Number
    Default: '65'
    MinValue: '65'
    MaxValue: '1000'
  QSS3BucketName:
    Type: String
    Default: aws-quickstart
  QSS3KeyPrefix:
    Type: String
    Default: quickstart-ribbon-sbc/
Conditions:
  # This condition is not used.
  EipOnPkt0: !Equals
    - 'true'
    - 'true'
  VolumeTypeIO1: !Equals
    - !Ref 'SBCVolumeType'
    - io1
  CreateVPCEndPoint: !Equals
    - !Ref 'CreateVPCEndPoint'
    - 'yes'
  EipForHFEManagementInterface: !Equals
    - !Ref 'HFEManagementNeedsEIP'
    - 'Yes'
  noVPCEndPointForMgt: !Equals
    - !Ref 'CreateVPCEndPoint'
    - 'no'
Rules:
  NameValidation:
    Assertions:
    - Assert:
      !Not
      - !Equal
        - !Ref 'SBCActiveInstanceName'
        - !Ref 'SBCPassiveInstanceName'
      AssertionDescription: "SBCActiveInstanceName and SBCPassiveInstanceName must be unique"
    - Assert:
      !Not
      - !Equal
        - !Ref 'SBCActiveInstanceName'
        - !Ref 'SBCSystemName'
      AssertionDescription: "SBCActiveInstanceName and SBCSystemName cannot be the same."
    - Assert:
      !Not
      - !Equal
        - !Ref 'SBCPassiveInstanceName'
        - !Ref 'SBCSystemName'
      AssertionDescription: "SBCPassiveInstanceName and SBCSystemName cannot be the same."
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
      Parameters:
        AvailabilityZones:
          Fn::Join:
            - ','
            - !Ref AvailabilityZones
        KeyPairName: !Ref KeyPairName
        PublicSubnet1CIDR: !Ref 'ManagementSubnetCIDR'
        PublicSubnet2CIDR: !Ref 'SBCExVoipCIDR'
        PublicSubnet3CIDR: !Ref 'HFEPublicCIDR'
        PrivateSubnet1CIDR: !Ref 'SBCHASubnetCIDR'
        PrivateSubnet2CIDR: !Ref 'SBCInVoipCIDR'
        PrivateSubnet3CIDR: !Ref 'HFEPrivateCIDR'
        NumberOfAZs: '1'
        VPCCIDR: !Ref 'VPCCIDR'
  SBCExVoipSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !GetAtt
      - VPCStack
      - Outputs.VPCID
      CidrBlock: !Ref 'PublicHFEPacketSubnetCIDR'
      AvailabilityZone: !Ref 'SBCAvailabilityZone'
      Tags:
      - Key: Name
        Value: !Sub "${SBCSystemName}-External Voip (ExVoip) Subnet"
  SBCManagementSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !GetAtt
      - VPCStack
      - Outputs.VPCID
      CidrBlock: !Ref 'ManagementSubnetCIDR'
      AvailabilityZone: !Ref 'SBCAvailabilityZone'
      Tags:
      - Key: Name
        Value: !Sub "${SBCSystemName}-Management Subnet"
  SBCHASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !GetAtt
      - VPCStack
      - Outputs.VPCID
      CidrBlock: !Ref 'SBCHASubnetCIDR'
      AvailabilityZone: !Ref 'SBCAvailabilityZone'
      Tags:
      - Key: Name
        Value: !Sub "${SBCSystemName}-HA Subnet"
  HFEPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !GetAtt
      - VPCStack
      - Outputs.VPCID
      CidrBlock: !Ref 'PublicHFEPacketSubnetCIDR'
      AvailabilityZone: !Ref 'SBCAvailabilityZone'
      Tags:
      - Key: Name
        Value: !Sub "${SBCSystemName}-HFE Public Subnet"
  HFEPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !GetAtt
      - VPCStack
      - Outputs.VPCID
      CidrBlock: !Ref 'PrivateHFESubnetCIDR'
      AvailabilityZone: !Ref 'SBCAvailabilityZone'
      Tags:
      - Key: Name
        Value: !Sub "${SBCSystemName}-HFE Public Subnet"
  SBCStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/ribbon-sbc.yaml
      Parameters:
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        HFEPublicSubnet: !Ref HFEPublicSubnet
        HFEPrivateSubnet: !Ref HFEPrivateSubnet
        KeyPairName: !Ref KeyPairName
        HFEManagementEIPAccessCIDR: !Ref HFEManagementEIPAccessCIDR
        SBCAvailabilityZone: !Ref SBCAvailabilityZone
        SBCExVoipSubnet: !Ref SBCExVoipSubnet
        SBCInternalVoipCIDR: !Ref SBCInternalVoipCIDR
        SBCManagementSubnet: !Ref SBCManagementSubnet
        SSHAccessCIDR: !Ref SSHAccessCIDR
        VPCID: !GetAtt
          - VPCStack
          - Outputs.VPCID