--- 
   
- debug: 
    msg: "{{ SBC_HOST_IP }}"

- name: change admin password 
  uri:
    url: "https://{{ SBC_HOST_IP }}/api/config/oam/localAuth/users/_operations/changePassword"
    method: POST
    user: "{{ SBC_EMA_USER }}"
    password: "{{ SBC_EMA_PASSWD_DEFAULT }}"
    validate_certs: no
    force_basic_auth: no
    follow_redirects: all
    body: "{{ lookup('file','../payload/changePassword.json') }}"
    body_format: json
    return_content: yes
    headers:
      Content-Type: "application/vnd.yang.operation+json"
    status_code: 200
    timeout: 10
