--- 
   
- debug: 
    msg: "{{ SBC_HOST_IP }}"

- name: configure Ingress IpInterface 
  uri:
    url: "https://{{ SBC_HOST_IP }}/api/config/addressContext/ADDR_CONTEXT/ipInterfaceGroup/INGRESS_LIG"
    method: POST
    user: "{{ SBC_EMA_USER }}"
    password: "{{ SBC_EMA_PASSWD }}"
    validate_certs: no
    force_basic_auth: no
    follow_redirects: all
    body: "{{ lookup('file','../payload/ipInterface_IN.json') }}"
    body_format: json
    return_content: yes
    headers:
      Content-Type: "application/vnd.yang.data+json"
    status_code: 201
    timeout: 10
