--- 
   
- debug: 
    msg: "{{ SBC_HOST_IP }}"

- name: configure Routing Label Route 
  uri:
    url: "https://{{ CURRENT_ACTIVE }}/api/config/global/callRouting/routingLabel/VRF_RL_IN"
    method: POST
    user: "{{ SBC_EMA_USER }}"
    password: "{{ SBC_EMA_PASSWD }}"
    validate_certs: no
    force_basic_auth: no
    follow_redirects: all
    body: "{{ lookup('file','../payload/routingLabelRoute_2.json') }}"
    body_format: json
    return_content: yes
    headers:
      Content-Type: "application/vnd.yang.data+json"
    status_code: 201
    timeout: 10
