--- 
   
- debug: 
    msg: "{{ SBC_HOST_IP }}"

- name: configure SIP Trunk Group Egress  
  uri:
    url: "https://{{ CURRENT_ACTIVE }}/api/config/addressContext/ADDR_CONTEXT/zone/ZONE8"
    method: POST
    user: "{{ SBC_EMA_USER }}"
    password: "{{ SBC_EMA_PASSWD }}"
    validate_certs: no
    force_basic_auth: no
    follow_redirects: all
    body: "{{ lookup('file','../payload/sipTrunkGroup_2.json') }}"
    body_format: json
    return_content: yes
    headers:
      Content-Type: "application/vnd.yang.data+json"
    status_code: 201
    timeout: 10
